# Generated by Django 2.2.2 on 2019-08-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20190806_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
