# Generated by Django 2.2 on 2020-04-26 15:49

from django.db import migrations

def create_data(apps, schema_editor):
    Product = apps.get_model('stocks', 'Product')
    Product(name="grapes", description="green fruit", quantity="10", unit_price="10",stock_level="100",created_by_id="1").save()

class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20190911_1401'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
