# Generated by Django 2.2.4 on 2019-09-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='current_stock_level',
            field=models.PositiveIntegerField(verbose_name='current stock level'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_stock_level',
            field=models.PositiveIntegerField(verbose_name='total stock level'),
        ),
    ]
