# Generated by Django 2.2.4 on 2019-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
