# Generated by Django 2.2.4 on 2019-09-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
