# Generated by Django 2.2.4 on 2019-09-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190910_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.PositiveIntegerField(verbose_name='total amount'),
        ),
    ]
